name: Push

on: 
  push:
    branches:
      - '**'
      
jobs:
  build-and-pack:
    runs-on: ubuntu-latest
    env:
      project: Byteology.GuardClauses
      
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Checkout
        uses: actions/checkout@v2
           
      - name: Restore
        run: dotnet restore
        
      - name: Sonarqube Begin
        run: | 
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /o:someorg /k:somekey /d:sonar.login=${{ secrets.SONAR_TOKEN }} /s:$GITHUB_WORKSPACE/SonarQube.Analysis.xml
          
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal --settings coverlet.runsettings --logger:trx
        
      - name: Sonarqube End
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Pack
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          version=$(grep -oP '(?<=<Version>).*?(?=</Version>)' ./${project}/*.csproj)
          version="${version}-rc-${{ github.run_number }}"
          dotnet pack ${project} -c Release /property:Version=${version} -o ./out --no-restore --no-build 
          dotnet nuget push ./out/*.nupkg \
          -s https://nuget.pkg.github.com/Byteology/index.json -k ${{ secrets.GITHUB_TOKEN }} \
          --skip-duplicate --no-symbols true
